version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - db_keys.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

