version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - db_keys.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - db_keys.env
  redis:
    image: "redis:alpine"
    ports:
      - 6378:6378
    command: redis-server
    volumes:
    - .tradeproject-redis:/data
  celery:
    build: .
    command: celery -A tradeproject worker -B
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - db_keys.env
      
volumes:
  static_volume:
