# Generated by Django 3.1.5 on 2021-01-19 12:21
from django.contrib.auth import get_user_model
from django.db import migrations


User = get_user_model()


def copy_item_to_watchlist(apps, schema_editor):
    Watchlist = apps.get_model('tradeapi', 'WatchList')
    Item = apps.get_model('tradeapi', 'Item')
    for user in User.objects.all():
        if Watchlist.objects.filter(user=user.id).exists():
            continue

        item = Item.objects.all().order_by("price")[0]

        wl = Watchlist.objects.create(user_id=user.id, item=item)
        wl.save()



class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0013_auto_20210118_1802'),
    ]

    operations = [
        migrations.RunPython(copy_item_to_watchlist),
    ]

